### ISSUE TITLE
[DOCS] Add example for py_nillion_client.PublicVariables or Add example on computing with created public elements.

### ISSUE THREAD

**Issue by manel1874** [NillionNetwork/nillion-docs#4]
Thank you for reading the docs and suggesting an improvement!

**What section of the docs could be improved? **
[Python client docs](https://nillion-builder-docs.vercel.app/pydocs/client.html) for `class py_nillion_client.PublicVariables(public_variables)` section.

**What part(s) of the docs would you like to see updated?**
It would be great to have an example for the docs below for the PublicVariables. It is not obvious what `the value is a encoded value` means,
```
class py_nillion_client.PublicVariables(public_variables)
This is a PublicVariable class used as a collection of public variables.

Parameters:
public_variables (dict) – Where the key is a named str and the value is a encoded value created from accompanying encoders

Return type:
[PublicVariables](https://nillion-builder-docs.vercel.app/pydocs/client.html#py_nillion_client.PublicVariables)
```

Example:
```python
    compute_id = await client.compute(
        cluster_id,
        bindings,
        [store_id],
        compute_secrets,
        py_nillion_client.PublicVariables({"my_public_"int: py_nillion_client.PublicVariableInteger(10)}),
    )
```

**Additional context**
Add any other context here.

**Comment by oceans404** [comment]
https://docs.nillion.com/python-client-reference#py_nillion_client.PublicVariables
