### ISSUE TITLE
[DOCS]Simple Suggestion

### ISSUE THREAD

**Issue by bennytimz** [NillionNetwork/nillion-docs#46]
Thank you for reading the docs and suggesting an improvement!

**First things first**
- If you have questions, ask in Discussions.
- Check Issues to make sure someone hasn't already opened a similar issue.

**What section of the docs could be improved? ** The bullet point where Nada was first mentioned
Please provide the title and link

**What part(s) of the docs would you like to see updated?**
Give as much detail as you can to help us understand the change you want to see. Why should the docs be changed? What additional information could be added? What is the expected outcome of adding the information?

**Additional context** I would like to see more information on what Nada is as an upcoming developer that i am
Add any other context here.

**Optional - ETH Address**
Optionally add your ETH Address here.0x773d95942878ce8f29E9B3B768d2180401820F95

**Comment by oceans404** [comment]
This issue doesn't have a suggestion for improving the docs.

**Comment by bennytimz** [comment]
Working on that,ser
