### ISSUE TITLE
[DOCS] Include Party ID in the description of Peer ID 

### ISSUE THREAD

**Issue by manel1874** [NillionNetwork/nillion-docs#9]
**What section of the docs could be improved?**

In the Python Client we use the method party_id(), which is a wrapper of peer ID. Should we include in the [concepts](https://docs.nillion.com/concepts) section some information saying peer ID is also denoted by party ID in the clients?

**Comment by oceans404** [comment]
https://docs.nillion.com/concepts#party-id
